### ISSUE TITLE
roclets attribute for r_pkg

### ISSUE THREAD

**Issue by siddharthab** [grailbio/rules_r#15]
r_pkg can take a list of strings as a "roclets" attribute to run roxygen on package source code before building it. This will automate a manual step that developers do frequently before running a build or test.

**Comment by hchauvin** [comment]
I thought about it and that's the right approach IMO.  You simply get rid of the 'NAMESPACE' file, it only lives in bazel-bin, and you complete the DESCRIPTION file with 'Collate'.  It means however you cannot simply 'cd' to the package folder and use barebone R.  Ultimately it needs a rule akin to devtools::install_local, but for Bazel.  This also runs contrary to the current logic of buildify in razel.R: here, the source of truth is not the BUILD file, but the NAMESPACE and DESCRIPTION files.

What do you think?

**Comment by siddharthab** [comment]
There are a few commits coming in the next week that will tackle the outstanding issues, including this one.

As for the issue of using barebones R, you can still use it, provided you couple with roxygen, which you should be doing anyway to avoid using stale files. Typically foundational packages are integrated into base R workflows (like knitr for vignettes) but roxygen, etc. have stayed out of it.

**Comment by siddharthab** [comment]
Resolved by 6ed3adb67f9dcaf97a4eab6746acc2629f5190da.
