### ISSUE TITLE
cc_deps should use the new Starlark C++ API

### ISSUE THREAD

**Issue by siddharthab** [grailbio/rules_r#31]
See https://github.com/bazelbuild/bazel/issues/4570 for progress on the API.

It is not quite ready yet, but this issue will track work on using the API to solve our long standing problem of obtaining PIC.

**Comment by Gawainus** [comment]
@siddharthab Hi Thanks for writing this repo. I am trying to use it to do a Rcpp wrapper around some c++ code. The cc_deps were specified and it was observed that the cc dependencies were compiled when I run `bazel build`. But there is no .so lib emitted in the final rpkg, just the R wrapper itself. Is this related to the "ong standing problem of obtaining PIC" you mentioned?

If not can you be a bit more explicit about how to use c++ dependencies in the doc? Many thanks.

**Comment by siddharthab** [comment]
@Gawainus Do you have a src directory in your package with some C/C++ code? You will need to have that much for R to actually compile a dynamically linked library for you and include it in your package.

**Comment by Gawainus** [comment]
@siddharthab No. To respect the existing code structure. I just did `cc_deps = ["//some/path:lib"]`. You mean I need to put all the C/C++ code in src? Or I just need some thing to trigger the compilation?

**Comment by siddharthab** [comment]
You just need something to trigger the compilation.

**Comment by siddharthab** [comment]
I think this is completely resolved as part of c143bca8f1e3c89787b4e4e5b9ced8748bd1fb15. I will open a new issue for future API changes when they happen.
