### ISSUE TITLE
document maintaining list of external packages

### ISSUE THREAD

**Issue by Marcus-Rosti** [grailbio/rules_r#44]
Noticed that dependencies aren't being downloaded from the bazel cache, but rather are redownloaded every time.

**Comment by siddharthab** [comment]
That should not happen. Is it happening if you run the same bazel command twice, without any other action in between? Are you noticing this for dependencies of other types?

**Comment by Marcus-Rosti** [comment]
I'll confirm tomorrow (I've been on vacation)

**Comment by Marcus-Rosti** [comment]
Oh I think I might know the issue @siddharthab, I think it's because I'm not listing all of the sha256 information. for instance this is how I've listed some of the deps.

```
"Package","Version","sha256"
"sparklyr","1.0.5","c5377feba05fb0b9873e17802e19dd07f9d191a76f6528eb12b5cb66dc1000ea"
"covr","3.4.0","e57d9c656b4ab50a7f9557dee422d8777efaf08ecde0fd8bfa5897ef4d9e845c"
"assertthat","0.2.1",""
"base64enc","0.1-3",""
"config","0.3",""
```

I couldn't figure out how to generate the dependencies I needed based on what your tooling so I just wrote a really simple script to do it.

```R
deps <- pkgDep(c("sparklyr", "covr"), enhances = FALSE, suggests = FALSE)
versions <- lapply(lapply(deps,packageVersion),toString)
all <- cbind(deps, versions)
allPlussha <- cbind(all, c(""))
colnames(allPlussha) <- c("Package", "Version", "sha256")
write.csv(allNames, "third_party/R/packages_from_r.csv",quote=c(1,2,3),row.names=FALSE)

```

**Comment by Marcus-Rosti** [comment]
oh okay I also think I understand better what you meant.

So I run a remote cache in our office with https://hub.docker.com/r/buchgr/bazel-remote-cache/ but I noticed that it's not downloading the deps from there, just posting them. It caches them between build commands locally, but doesn't pull them from that on `bazel clean --expunge; bazel build //...`

**Comment by siddharthab** [comment]
Yeah, repositories have their own cache specified with `repository_cache` flag. But the exact nature is a mystery to me as well.

**Comment by siddharthab** [comment]
Would you benefit from improved documentation in how to generate the package list CSV?

**Comment by Marcus-Rosti** [comment]
yeah! the dep generation docs would really help
