### ISSUE TITLE
Is it possible to include a py_binary in the deps of a r_binary?

### ISSUE THREAD

**Issue by sophieball** [grailbio/rules_r#48]
I wanted to use my R code to call a python code that is also built with bazel. Currently, I have to build them as two separate targets (a py_binary and a r_binary). But is there a way that I can put the py_binary as a `deps` for the r_binary, so that when I build the r_binary, it will automatically build the py_binary?

**Comment by siddharthab** [comment]
Hey, yes. Definitely. I use the `inst_file` attribute in my `r_pkg` label. For example,

```bzl
inst_files = {
  "//third_party/python/awscli:aws": "exec",
},
```

will copy the aws CLI into the exec directory in your built package, given by `system.file("exec", package = pkgname)`.

Let me know if this helps.

**Comment by sophieball** [comment]
Great! Thanks!
