### ISSUE TITLE
r_package macro doesn't expose all r_pkg options

### ISSUE THREAD

**Issue by deadmoose** [grailbio/rules_r#50]
Just got bit trying to set `stamp` & `metadata` on an `r_package`, but all it passes through is the srcs & deps.

I'm not sure if there's any particular reason not to just let the `r_package` take `**kwargs` & directly pass it along to its underlying `r_pkg` ?

Though honestly, looking at it, I probably would've written `r_package` purely in terms of kwargs. Then it's a 100% transparent drop-in replacement, plus you don't need to worry at all about updating the convenience wrapper when the real thing adds new options.

E.g.

```
def r_package(name, **kwargs):
    r_pkg(
        name = name,
        **kwargs,
    )
    r_library(
        name = "library",
        pkgs = [":%s" % name],
        tags = ["manual"],
    )
```

**Comment by siddharthab** [comment]
Apologies for the delayed response. I am not very active in maintaining this now. Mostly the system has been stable enough to not need many updates.

There was no particular reason to do this. Just that these macros were written very early on and I had very limited knowledge of pythonic syntax and that kwargs is a thing. If writing with the knowledge I have now, I would have written at least `r_package` as you describe. Not so sure about `r_package_with_test`.

Maybe I should just deprecate these macros or remove them entirely. They don't really contain any logic, and so the additional opaqueness is not worth it.
