### ISSUE TITLE
Long R_LIBS (R_LIBS_DEPS) not parsed properly by R CMD INSTALL

### ISSUE THREAD

**Issue by gfinak** [grailbio/rules_r#51]
When the list of dependencies gets really long, R CMD INSTALL no longer sees the installed dependencies when building a package.
I can confirm this by shortening R_LIBS_DEPS, or by installing the packages that aren't found into the R/site-library, then R CMD INSTALL sees them properly.
Two questions: 
1. is there a known work-around?
2. Is it possible to have rules_r install to a "global" R_LIBS directory rather than package-specific R_LIBS directories that then get joined into a long ungainly string?
I can clarify this issue further if needed.
This is on ubuntu.

**Comment by mst** [comment]
We had a similar issue and found that there may be a problem with env var interpolation with `Renviron`:

```
root@46ac8f61aa7b:/# R_LIBS=$(printf '=%.0s' {1..10000})  R -s -e 'Sys.getenv("R_LIBS")'
[1] "${R_LIBS-/usr/local/lib/R/site-library:/usr/local/lib/R/library}"
root@46ac8f61aa7b:/# R -s -e 'Sys.getenv("R_LIBS")'
[1] "/usr/local/lib/R/site-library:/usr/local/lib/R/library"
root@46ac8f61aa7b:/#
```

We found a `/usr/local/lib/R/etc/Renviron` that contained
```
[...]
R_LIBS=${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library'}
[...]
```

To resolve our issue, we ended up removing the line from our `Renviron`s :

```
find / -name "Renviron" | xargs sed -i -E -e "/R_LIBS=\\$\{R_LIBS-/d"
```

Not sure if that relates to your issue, but it definitely sounds very similar, maybe worth a try.

**Comment by siddharthab** [comment]
Hello,

Thank you @gfinak for reporting this issue. I did observe issues with R 3.3 but I have not seen them since then. So I defaulted to using this behaviour.

Copying all the deps to a unique temporary directory for every build can be very inefficient, but I can perhaps try symlinking them.

Is there a way I can reproduce this issue? No worries if not.

Thank you @mst for your hypothesis. Interpolation does have its own restrictions. If I can recreate the specific issue, I will try with and without interpolation.

Sid

**Comment by gfinak** [comment]
Thanks, both. Apologies, that I didn't provide a reprex, but this has been difficult to isolate. Glad to hear I'm not alone, and @mst I'll try your approach and report back. @siddharthab that's a good point. I'm new to Bazel and still finding my way around. I'll let you know shortly if this resolves the issue.

**Comment by gfinak** [comment]
@mst  can confirm that editing `Renviron` resolved this issue. 
This was on R 4.0.

@siddharthab  medium-term would you consider a patch to this that doesn't require editing `Renviron`?
I'm happy to take a stab at it if it creeps up again for me in the future, but personally, for now, I'm satisfied with the work-around.

**Comment by siddharthab** [comment]
Thanks for confirming that interpolation was the issue. I will look for workarounds.

**Comment by siddharthab** [comment]
Working on this now.
