### ISSUE TITLE
how to install r check deps into system R library path

### ISSUE THREAD

**Issue by mikejiang** [grailbio/rules_r#54]
here is part of my BUILD file
```
PKG_NAME = "flowWorkspace"
PKG_CHECK_DEPS = [
    "@R_knitr//knitr:knitr",
    "@R_ggcyto//:ggcyto",
    
]
r_pkg(
    name = PKG_NAME,
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD",
            "src/Makevars",
        ],
    ),
    cc_deps = [
        ":flowWorkspace_hdrs",
    ],
    config_override = ":empty",
    makevars = ":flowworkspace_makevars",
    pkg_name = "flowWorkspace",
    deps = [
        "@R_Biobase//Biobase",
        "@R_DelayedArray//DelayedArray",
        "@R_RBGL//RBGL",
        "@R_Rcpp//Rcpp",
        "@R_RcppParallel//RcppParallel",
         ],
)

r_library(
    name="library",
    pkgs = [PKG_NAME]
)

r_pkg_test(
    name = "check",
    timeout = "short",
    pkg = PKG_NAME,
    check_args = ["--no-codoc", "--no-manual", "--no-build-vignettes"],
    suggested_deps = PKG_CHECK_DEPS,
)
```
I have encountered a test error during R CMD check (invoked by `bazel run packages/flowWorkspace:check` )

I'd like to reproduce and troubleshoot the test error interactively at regular R console with devtools:test() 
I know all the r packages and its deps can be copied to system R library path by running the `r_library` target (i.e. bazel run packages/flowWorkspace:library), but it will miss the packages defined in PKG_CHECK_DEPS.
I can't paste these to deps list of r_pkg rule since that will fail the bazel build due to some circular dependencies from `suggests` deps of r package.

I wonder if there is a convenient way to copy the packages listed in PKG_CHECK_DEPS (i.e. `bazel-out/k8-fastbuild/bin/packages/flowWorkspace/check.runfiles/` I guess) to system R path instead of manually doing it.

**Comment by siddharthab** [comment]
Hi! Sorry for the delay. You can make an additional `r_library` target, or edit the existing one to also include PKG_CHECK_DEPS. That way, you can avoid the circular dependency.

Option 1:
```python
r_library(
    name="library",
    pkgs = [PKG_NAME] + PKG_CHECK_DEPS,
)
```

Option 2:
```python
r_library(
    name="all_deps",
    pkgs = PKG_DEPS + PKG_CHECK_DEPS,
)
```

I am going to close this now, but please reopen if this does not work for you.
