### ISSUE TITLE
Question on header paths

### ISSUE THREAD

**Issue by depthwise** [grailbio/rules_r#81]
@siddharthab, I'm trying to use the newest `master` in our repo, and it's failing to build some of the packages we have in-tree, meaning that their source code is directly checked in. The reason why this seems to be failing is because most of our `#include`s use full paths wrt root of repo, which works pretty well with our tooling (YouCompleteMe etc) and eliminates ambiguity wrt their locations.

This _used to_ work, but now it doesn't. The amound of changes between the previous release of `rules_r` and current `master` is quite substantial. Would you hazard a guess on what could possibly be causing this and what I could tweak so `r_pkg` is able to find headers referenced with their full path?

**Comment by siddharthab** [comment]
Hi,

I think it's possible that we may have started working from a different directory, but I don't see any such change in the code. Can you build your package with `env_vars = {"BAZEL_R_VERBOSE"="true"}` as an attribute? In both the previous release that worked for you, and the current master. That will give you the exact compiler commands that were used.

I think a proper solution for this would be to add `CPPFLAGS += -iquote _EXEC_ROOT_` in the file in the makevars attribute for either the r_pkg or r_toolchain. `_EXEC_ROOT_` is a marker that I replace with the absolute path to the bazel execution root.

As a bonus, you can also do `git bisect` with `--override_repository` flag to bazel to get the exact commit that broke the behaviour for you.

**Comment by depthwise** [comment]
That's something to try, thanks, although the build command does not seem to have anything suspicious in a side by side comparison. I'll close for now and re-activate if I get nowhere with this.

**Comment by depthwise** [comment]
Didn't get very far with this, but this seems vaguely sandbox related, as if the sources aren't there, which I suspect they aren't, when running under the sandbox. If I disable the sandbox, things seem to build OK. Moreover, if I unpack the archive rules_r is creating and run the same `make` commands (stripping out the sandbox-related parts of the paths), things build fine, too, which leads me to believe that the header in question is not mapped to the right location in the sandbox. It is in the `rules_r` generated `*.tar.gz` however, but the path there is with respect to the package root, not repo root.

**Comment by depthwise** [comment]
OK, I've tracked this down. This is because 2-nd stage build no longer includes `src_files_sans_tests`, so my hunch was right. Now, I suspect this is the right thing to do for rules_r in general. It's just not the right thing for us when building in-tree.
