### ISSUE TITLE
Seems like C_SO_LD_FLAGS has no effect when external *.so is included

### ISSUE THREAD

**Issue by depthwise** [grailbio/rules_r#82]
Looks like it meant to be written into Makevars file now, but it doesn't end up there - it's initialized after Makevars is written.

Here's where it's written: https://github.com/grailbio/rules_r/blob/master/R/scripts/build_pkg_src.sh#L18

And here's where some more stuff is added to it: https://github.com/grailbio/rules_r/blob/master/R/scripts/build_pkg_src.sh#L50

What this means for us is, the `*.so` we want to link to is included into the archive, but the main module `*.so` doesn't link to it, since it has no flags telling it to do so.

**Comment by siddharthab** [comment]
My apologies. I thought this was tested, but really not. There is this constant tension in this project for feature support, good test coverage, and the number of people using the feature. I give less than 5% of my time to the maintenance of this project, and so some things will feel less polished and less tested than others. I think I have fixed the bug in my linked PR, but I don't have the time to write a proper test case for it right now. Please can you try out the PR to see if it works for you?

Thank you for showing your support.

**Comment by depthwise** [comment]
Understandable. Arguably this is not the most frequently used functionality, and as such it'll probably be flakier than the better trodden paths. In fact we'd prefer static linking in all cases, it's just not doable with R, since multiple *.so's can be loaded in the same process, and static initialization messes things up.
