### ISSUE TITLE
r_toolchain to support setting r and rscript using Bazel target names/labels

### ISSUE THREAD

**Issue by borancar** [grailbio/rules_r#87]
I'd like to have r_toolchain r and rscript set using Bazel target names/labels to support Bazel itself providing R, like rules_nixpkgs, or even Bazel building R.

E.g.:

```
r_toolchain(
    name = "r_toolchain_linux",
    r = "@Rnix//:bin/R",
    rscript = "@Rnix//:bin/Rscript",
```

**Comment by siddharthab** [comment]
Can you check the attached pull request if it works for you? I have not really tested it because we don't have nix setup in this repo.

**Comment by siddharthab** [comment]
Hold on. It's not quite ready.
